# Generated by Django 3.2.9 on 2021-12-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
    ]
